# Generated by Django 3.0.6 on 2021-02-14 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210201_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_created',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_updated',
            new_name='publishedAt',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_updated',
            new_name='updatedAt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
        migrations.AddField(
            model_name='article',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='publishedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
