# Generated by Django 3.0.6 on 2021-01-31 02:21

import ckeditor.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import django_extensions.db.fields
import fontawesome_5.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDePromocoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDoLocal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('icone', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('imagem', models.ImageField(default='category-default.jpg', upload_to='locais/categoria/imagem/%Y/%m/%d/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('categoriaBase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locais.CategoriaDoLocal')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='CategoriaPromocional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('imagem', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['nome', 'id'])),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria Promocional',
                'verbose_name_plural': 'Categorias Promocionais',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/%d/')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=7, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('ativo', models.BooleanField(default=False)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('dataPublicacao', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['id', 'nome'])),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.CategoriaDoLocal')),
                ('estado', smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado', to='localidades.Estado')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio', to='localidades.Municipio')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pais', to='localidades.Pais')),
                ('responsavel', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sites', models.ManyToManyField(related_name='site', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'db_table': 'local',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDeLocal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('icone', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('imagem', models.ImageField(default='category-default.jpg', upload_to='locais/tipodelocal/imagem/%Y/%m/%d/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('aprovado', models.BooleanField(default=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Local',
                'verbose_name_plural': 'Tipos de Locais',
            },
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('precoReal', models.CharField(max_length=7)),
                ('precoPromocional', models.CharField(max_length=7)),
                ('linkDeCompra', models.CharField(max_length=200)),
                ('info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fotoDoLocal', models.ImageField(blank=True, null=True, upload_to='promo/%Y/%m/%d/')),
                ('prazoDaOferta', models.DateField()),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['nome', 'id'])),
                ('categorias', models.ManyToManyField(through='locais.BaseDePromocoes', to='locais.CategoriaPromocional')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.Local')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.CreateModel(
            name='GaleriaDeFotosDosLocais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='locais/fotos/%Y/%m/%d/')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.Local')),
            ],
            options={
                'verbose_name': 'Galeria de Fotos',
                'verbose_name_plural': 'Galeria de Fotos',
            },
        ),
        migrations.AddField(
            model_name='categoriapromocional',
            name='promocao',
            field=models.ManyToManyField(through='locais.BaseDePromocoes', to='locais.Promocoes'),
        ),
        migrations.AddField(
            model_name='basedepromocoes',
            name='categorias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.CategoriaPromocional'),
        ),
        migrations.AddField(
            model_name='basedepromocoes',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.Promocoes'),
        ),
    ]
