# Generated by Django 3.0.6 on 2021-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='endereco',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
