# Generated by Django 3.0.6 on 2021-02-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0005_contatodolocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatodolocal',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatosDoLocal', to='locais.Local'),
        ),
    ]
