# Generated by Django 3.0.6 on 2021-02-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0006_contatodolocal_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatodolocal',
            name='identificador',
        ),
    ]
