# Generated by Django 3.0.6 on 2021-01-31 02:21

import ckeditor_uploader.fields
import cloudinary.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import django_extensions.db.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=1500)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['id', 'titulo'])),
                ('descrição', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=7, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('dataConclusao', models.DateTimeField(blank=True, null=True)),
                ('poder', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PUBLICO', max_length=10)),
                ('estadoDaOcorrencia', models.CharField(choices=[('AGUARDANDO', 'Não Respondida'), ('PROGRESSO', 'Em tratativa'), ('CONCLUIDA', 'Concluída'), ('INCONCLUIDA', 'Iniciada, mas abandonada')], default='AGUARDANDO', max_length=20)),
                ('anonimo', models.BooleanField(default=False)),
                ('deletado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-dataCriacao',),
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaFotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ocorrenciaimg')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='issueTracker.Ocorrencia')),
            ],
            options={
                'verbose_name': 'Imagens das Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(default='category-default.jpg', upload_to='ocorrencias/categorias')),
                ('aprovada', models.BooleanField(default=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('dataAtualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'unique_together': {('nome',)},
            },
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='issueTracker.OcorrenciaCategoria'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='estado',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadoOcorrencia', to='localidades.Estado'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipioOcorrencia', to='localidades.Municipio'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paisOcorrencia', to='localidades.Pais'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='reclamante',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='seguir',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ocorrencia',
            unique_together={('id', 'titulo')},
        ),
    ]
