# Generated by Django 3.0.6 on 2021-02-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciacategoria',
            name='nome',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ocorrenciacategoria',
            name='slug',
            field=models.SlugField(max_length=1000),
        ),
    ]
