# Generated by Django 3.0.6 on 2021-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0003_auto_20210203_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='bairro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='complemento',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
