# Generated by Django 3.0.6 on 2021-02-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTracker', '0004_auto_20210203_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='endereco',
            field=models.CharField(max_length=1000),
        ),
    ]
