# Generated by Django 3.0.6 on 2021-02-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.formatChecker
import taggit_selectize.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('content', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[posts.formatChecker.FileValidator(content_types=('video/x-msvideo', 'image/bmp', 'image/gif', 'image/jpeg', 'video/quicktime', 'application/pdf', 'video/mp4', 'video/mpeg', 'audio/mpeg', 'image/png'), max_size=102400)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('publishedAt', models.DateTimeField(auto_now=True)),
                ('tags', taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
