# Generated by Django 3.0.6 on 2021-02-13 22:31

from django.db import migrations, models
import posts.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[posts.formatChecker.FileValidator(content_types=('video/x-msvideo', 'image/bmp', 'image/gif', 'image/jpeg', 'video/quicktime', 'application/pdf', 'video/mp4', 'video/mpeg', 'audio/mpeg', 'image/png'), max_size=104857600)]),
        ),
    ]
